pipeline:
  backend:
    image: node
    commands:
      - npm install
      - npm test
  notify:
    image: plugins/slack
    secrets: [slack_hook]
    webhook: ${SLACK_HOOK}
    channel: builds
    username: drone
